import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

const eslintConfig = [
  {
    // next-env.d.ts is generated by Next and uses triple-slash references.
    ignores: [
      // Any Next build directory, whatever NEXT_DIST_DIR was set to.
      ".next*/**",
      "node_modules/**",
      "out/**",
      // Agent worktrees are whole second checkouts living inside this one.
      // Gitignore does not exclude them from ESLint, so without this a lint
      // run reports tens of thousands of problems from other checkouts'
      // build output.
      ".claude/**",
      "next-env.d.ts",
      // Generated by Payload, regenerated by `npm run payload:migrate:create`
      // and `npm run payload:importmap`. Committed because deploys need them,
      // not authored.
      "src/migrations/**",
      "src/app/(payload)/admin/importMap.js",
    ],
  },
  ...coreWebVitals,
  ...typescript,
  {
    rules: {
      // New in eslint-config-next 16. It fires on six pre-existing call sites:
      // SearchSelect, OrderReceived, HeroHeadlineV2Scramble,
      // HeroHeadlineV2Wipe, ShopFilters and SevenWidget. Each is a real
      // cascading-render smell worth fixing, but fixing them means changing
      // state logic in components whose interaction flows the parity gate only
      // partially covers -- so they are addressed as each component is ported,
      // not inside a framework upgrade that has to stay visually inert.
      // Restore to "error" once the last of the six is ported.
      "react-hooks/set-state-in-effect": "warn",
    },
  },
];

export default eslintConfig;
