import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

const eslintConfig = [
  {
    // next-env.d.ts is generated by Next and uses triple-slash references.
    ignores: [
      ".next/**",
      ".next-verify/**",
      ".next-parity/**",
      "node_modules/**",
      "out/**",
      "next-env.d.ts",
    ],
  },
  ...coreWebVitals,
  ...typescript,
  {
    rules: {
      // New in eslint-config-next 16. It fires on six pre-existing call sites:
      // SearchSelect, OrderReceived, HeroHeadlineV2Scramble,
      // HeroHeadlineV2Wipe, ShopFilters and SevenWidget. Each is a real
      // cascading-render smell worth fixing, but fixing them means changing
      // state logic in components whose interaction flows the parity gate only
      // partially covers -- so they are addressed as each component is ported,
      // not inside a framework upgrade that has to stay visually inert.
      // Restore to "error" once the last of the six is ported.
      "react-hooks/set-state-in-effect": "warn",
    },
  },
];

export default eslintConfig;
